source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'mongoid', '~> 7.0'
gem 'require_all'
gem "bunny", ">= 2.9.2"

group :test, :development do
  gem 'rspec'
  gem 'rack-test'
  gem 'factory_bot'
  gem 'faker'
  gem 'database_cleaner-mongoid'
end
