source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'require_all'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'sequel', '~> 5.55'

group :test, :development do
  gem 'rspec'
  gem 'rack-test'
  gem 'factory_bot'
  gem 'faker'
  gem 'database_cleaner-sequel'
end
